<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Invtypes_model extends CI_Model
{

    public $table = 'invtypes';
    public $id = 'typeID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
	
	function get_by_groupid($groupID)
    {
        $this->db->where('groupID', $groupID);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('typeID', $q);
	$this->db->or_like('groupID', $q);
	$this->db->or_like('typeName', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('mass', $q);
	$this->db->or_like('volume', $q);
	$this->db->or_like('capacity', $q);
	$this->db->or_like('portionSize', $q);
	$this->db->or_like('raceID', $q);
	$this->db->or_like('basePrice', $q);
	$this->db->or_like('published', $q);
	$this->db->or_like('marketGroupID', $q);
	$this->db->or_like('iconID', $q);
	$this->db->or_like('soundID', $q);
	$this->db->or_like('graphicID', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('typeID', $q);
	$this->db->or_like('groupID', $q);
	$this->db->or_like('typeName', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('mass', $q);
	$this->db->or_like('volume', $q);
	$this->db->or_like('capacity', $q);
	$this->db->or_like('portionSize', $q);
	$this->db->or_like('raceID', $q);
	$this->db->or_like('basePrice', $q);
	$this->db->or_like('published', $q);
	$this->db->or_like('marketGroupID', $q);
	$this->db->or_like('iconID', $q);
	$this->db->or_like('soundID', $q);
	$this->db->or_like('graphicID', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Invtypes_model.php */
/* Location: ./application/models/Invtypes_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-10 04:49:50 */
/* http://harviacode.com */